# Generated by Django 3.0.4 on 2020-03-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, null=True)),
                ('status', models.CharField(default='在职', max_length=32)),
                ('rank', models.CharField(default='工程师', max_length=32)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Management.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='mgr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Management.personnel'),
        ),
    ]
