# Generated by Django 3.0.4 on 2020-03-24 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_id', models.CharField(max_length=24, unique=True)),
                ('prj_name', models.CharField(default='未定', max_length=48, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
                ('product_model', models.CharField(default='未定', max_length=36, null=True, unique=True)),
                ('prj_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('status', models.CharField(default='预备', max_length=32, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creby', to='apps.Management.personnel')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgrby', to='apps.Management.personnel')),
            ],
        ),
    ]
