# Generated by Django 3.0.4 on 2020-03-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='statement',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
