# Generated by Django 3.0.4 on 2020-03-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20200324_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='condition',
            field=models.IntegerField(choices=[(0, '按时完成'), (1, '按时'), (2, '延期'), (3, '延误'), (4, '取消'), (5, '延期完成')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=48, null=True)),
                ('t_start_time', models.DateField(null=True)),
                ('t_end_time', models.DateField(null=True)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('condition', models.IntegerField(choices=[(0, '按时完成'), (1, '按时'), (2, '延期'), (3, '延误'), (4, '取消'), (5, '延期完成')], default=1, null=True)),
                ('remark', models.CharField(default='暂无', max_length=100, null=True)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Management.Project')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parenttask', to='apps.Management.Task')),
                ('principle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Management.personnel')),
            ],
        ),
    ]
