# Generated by Django 3.0.4 on 2020-03-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20200325_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='condition',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '延期'), (3, '延误'), (4, '取消'), (5, '完成'), (6, '延期完成')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '延期'), (3, '延误'), (4, '取消'), (5, '完成'), (6, '延期完成')], default=0, null=True),
        ),
    ]
