# Generated by Django 3.0.4 on 2020-03-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_auto_20200325_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonToTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='暂无', max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Management.personnel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Management.Task')),
            ],
        ),
    ]
