# Generated by Django 3.0.4 on 2020-03-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_persontotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
