# Generated by Django 3.0.4 on 2020-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_task_task_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statement',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
