# Generated by Django 3.0.4 on 2020-03-31 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_auto_20200327_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '预警'), (3, '延期'), (4, '取消'), (5, '完成'), (6, '延期完成')], default=0, null=True),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_title', models.CharField(max_length=48)),
                ('remark', models.CharField(default='暂无', max_length=200, null=True)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Management.Task')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Management.personnel')),
            ],
        ),
    ]
