# Generated by Django 3.0.4 on 2020-03-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20200331_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='duration',
        ),
        migrations.AddField(
            model_name='problem',
            name='condition',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '预警'), (3, '延期'), (4, '取消'), (5, '完成'), (6, '延期完成')], default=0, null=True),
        ),
    ]
