# Generated by Django 3.0.4 on 2020-04-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20200331_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=80)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Management.Project')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Management.Task')),
            ],
        ),
    ]
