# Generated by Django 3.0.4 on 2020-04-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expect_end_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='real_end_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
