# Generated by Django 3.0.4 on 2020-04-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_auto_20200403_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='parent_prob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Management.Problem'),
        ),
    ]
